// Automatically generated by protocolgen.GenJava. DO NOT MODIFY
package codeprober.protocol.data;

import org.json.JSONObject;

public class AsyncResult implements codeprober.util.JsonUtil.ToJsonable {
  public static enum Type {
    job,
    sync,
  }
  private static final Type[] typeValues = Type.values();

  public final Type type;
  public final Object value;
  private AsyncResult(Type type, Object value) {
    this.type = type;
    this.value = value;
  }
  public AsyncResult(java.io.DataInputStream src) throws java.io.IOException {
    this(new codeprober.protocol.BinaryInputStream.DataInputStreamWrapper(src));
  }
  public AsyncResult(codeprober.protocol.BinaryInputStream src) throws java.io.IOException {
    this.type = typeValues[src.readInt()];
    switch (this.type) {
    case job:
        this.value = src.readLong();
        break;
    case sync:
    default:
        this.value = new org.json.JSONObject(src.readUTF());
        break;
    }
  }
  public static AsyncResult fromJob(long val) { return new AsyncResult(Type.job, val); }
  public static AsyncResult fromSync(org.json.JSONObject val) { return new AsyncResult(Type.sync, val); }

  public boolean isJob() { return type == Type.job; }
  public long asJob() { if (type != Type.job) { throw new IllegalStateException("This AsyncResult is not of type job, it is '" + type + "'"); } return (long)value; }
  public boolean isSync() { return type == Type.sync; }
  public org.json.JSONObject asSync() { if (type != Type.sync) { throw new IllegalStateException("This AsyncResult is not of type sync, it is '" + type + "'"); } return (org.json.JSONObject)value; }

  public static AsyncResult fromJSON(JSONObject obj) {
    final Type type;
    try { type = Type.valueOf(obj.getString("type")); }
    catch (IllegalArgumentException e) { throw new org.json.JSONException(e); }
    switch (type) {
    case job:
      try {
        final long val = obj.getLong("value");
        return fromJob(val);
      } catch (org.json.JSONException e) {
        throw new org.json.JSONException("Not a valid AsyncResult", e);
      }
    case sync:
    default:
      try {
        final org.json.JSONObject val = obj.getJSONObject("value");
        return fromSync(val);
      } catch (org.json.JSONException e) {
        throw new org.json.JSONException("Not a valid AsyncResult", e);
      }
    }
  }

  public JSONObject toJSON() {
    final JSONObject ret = new JSONObject().put("type", type.name());
    switch (type) {
    case job:
      ret.put("value", ((long)value));
      break;
    case sync:
    default:
      ret.put("value", ((org.json.JSONObject)value));
      break;
    }
    return ret;
  }
  public void writeTo(java.io.DataOutputStream dst) throws java.io.IOException {
    writeTo(new codeprober.protocol.BinaryOutputStream.DataOutputStreamWrapper(dst));
  }
  public void writeTo(codeprober.protocol.BinaryOutputStream dst) throws java.io.IOException {
    dst.writeInt(type.ordinal());
    switch (type) {
    case job:
      dst.writeLong(((long)value));
      break;
    case sync:
    default:
      dst.writeUTF(((org.json.JSONObject)value).toString());
      break;
    }
  }
}
