package codeprober.textprobe;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

import codeprober.textprobe.ScannerTokenSource.StoppingPoint;
import codeprober.textprobe.ast.Container;
import codeprober.textprobe.ast.Document;
import codeprober.textprobe.ast.Expr;
import codeprober.textprobe.ast.Label;
import codeprober.textprobe.ast.Position;
import codeprober.textprobe.ast.Probe;
import codeprober.textprobe.ast.PropertyAccess;
import codeprober.textprobe.ast.Query;
import codeprober.textprobe.ast.QueryAssert;
import codeprober.textprobe.ast.QueryHead;
import codeprober.textprobe.ast.TypeQueryHead;
import codeprober.textprobe.ast.VarDecl;
import codeprober.textprobe.ast.VarUse;

/**
 * An LL(3) text probe parser implementation. Tokens are generated by
 * {@link ScannerTokenSource} and parsed here.
 * <p>
 * The parser supports the legacy implicit string conversion
 * ("cpr.permitImplicitStringConversion") by pre-processing the scanner token
 * stream and synthesizing a STRING token if necessary. This pre-processing is
 * a good third of the total parser size and should be removed/cleaned up once
 * we no longer support implicit string conversion.
 * <p>
 * The (3) in LL(3) is necessary to disambiguate "[[$id:=" and "[[$id=".
 */
public class LLParser {

	private final String src;
	private final List<ScannerToken> tokens;
	private int nextTokenIdx = 0;

	public LLParser(String src, List<ScannerToken> tokens) {
		this.src = src;
		this.tokens = tokens;
	}

	/**
	 * Parse all text probes in the given strings. Parsing can never fail - for
	 * unexpected inputs, this simply returns a document with zero
	 * containers/probes.
	 * <p>
	 * The document contains a number of containers, which represent "[[", "]]", and
	 * the content in between (or different brackets depending on how
	 * <code>startBracket</code> and <code>endBracket</code> is specified. Each
	 * container in turn contains zero or one probes (see
	 * {@link Container#probe()}). If the probe is <code>null</code>, then it means
	 * that the content inside the container is empty, or of an unexpected syntax.
	 * Handling empty/unexpected syntax can be important for language services
	 * (completion/hover/etc).
	 *
	 */
	public static Document parse(String s, char startBracket, char endBracket) {
		final String[] lines = s.split("\n");
		List<Container> containers = new ArrayList<>();

		for (int lineIdx = 0; lineIdx < lines.length; ++lineIdx) {
			parseLine(lineIdx, lines[lineIdx], startBracket, endBracket, containers);
		}

		return new Document(new Position(1, 1), // Start
				new Position(lines.length + 1, 1), // End
				containers);
	}

	private static void parseLine(int lineIdx, String line, char startBracket, char endBracket, List<Container> out) {
		final int lineNumber = lineIdx + 1; // 1-based line numbers

		int col = -1;
		final String startStr = String.valueOf(startBracket) + String.valueOf(startBracket);
		outer: while ((col = line.indexOf(startStr, col + 1)) != -1) {
			if (col < line.length() - 2 && line.charAt(col + 2) == startBracket) {
				// More than 2 opening brackets in a row. Skip ahead
				continue;
			}

			int startCol = col + 1; // 1-based column

			final ScannerTokenSource sts = new ScannerTokenSource(line, startBracket, endBracket, col, lineNumber,
					startCol);
			List<ScannerToken> tokens = new ArrayList<>();
			StoppingPoint decision = sts.scanUntilDecisionPoint(tokens);
			if (decision == StoppingPoint.IMPLICIT_STRING) {
				// Right-hand side of comparison.
				// In the "old" grammar, this supported automatic string literal conversions
				final ScannerToken next = sts.next();
				// After an EQ is either:
				// 1): Nothing, syntax sugar for empty string
				// 2): A query
				// 3): Anything, wrapped as a String expr

				if (next != null && next.type == ScannerTokenType.DOLLAR) {
					// Maybe case 2, don't know until we have parsed it
					int preTokensSize = tokens.size();
					int preOffset = sts.getOffset();

					tokens.add(next);
					scanNext: while (true) {
						final ScannerToken queryTok = sts.next();
						if (queryTok == null) {
							tokens.subList(preTokensSize, tokens.size()).clear();
							sts.setOffset(preOffset);
							break scanNext;
						}
						tokens.add(queryTok);
						if (queryTok.type == ScannerTokenType.CONTAINER_CLOSE) {
							final Container c = new LLParser(line, tokens).parseContainer();
							if (c != null) {
								// Case 2 success!
								out.add(c);
								col = c.end.column;
								continue outer;
							}
							// Else, case 2 fail. Restore scanner and proceed down to case 3.
							tokens.subList(preTokensSize, tokens.size()).clear();
							sts.setOffset(preOffset);
							break scanNext;

						}
					}
					// Fall down to case 3
				}
				// Else, everything until the closing brackets are an implicit string.
				if (next != null && next.type == ScannerTokenType.CONTAINER_CLOSE) {
					// Special case: empty string
					// TODO case 1
					tokens.add(new ScannerToken(ScannerTokenType.STRING, //
							new Position(lineNumber, next.start.column), //
							new Position(lineNumber, next.start.column), //
							""));
					tokens.add(next);
					final Container c = new LLParser(line, tokens).parseContainer();
					if (c != null) {
						out.add(c);
						continue outer;
					}
					col = next.end.column;
					continue outer;
				}
				final int strStart = next == null ? sts.getOffset() + 1 : next.start.column;
				for (int endCol = strStart - 1; endCol < line.length() - 1; ++endCol) {
					if (line.charAt(endCol) == endBracket //
							&& line.charAt(endCol + 1) == endBracket //
							&& ((endCol == line.length() - 2) || line.charAt(endCol + 2) != endBracket)) {

						tokens.add(new ScannerToken(ScannerTokenType.STRING, //
								new Position(lineNumber, strStart), //
								new Position(lineNumber, endCol), //
								line.substring(strStart - 1, endCol)));
						tokens.add(
								new ScannerToken(ScannerTokenType.CONTAINER_CLOSE, new Position(lineNumber, endCol + 1), //
										new Position(lineNumber, endCol + 2), //
										null));
						final Container c = new LLParser(line, tokens).parseContainer();
						if (c != null) {
							out.add(c);
							continue outer;
						}
						col = endCol + 2;
						continue outer;

					}
				}
				// Else, found no container close on this line.
				break outer;
			}

			switch (decision) {
			case CLOSING: {
				final Container c = new LLParser(line, tokens).parseContainer();
				if (c != null) {
					out.add(c);
					continue outer;
				}
				break;
			}

			case EOF:
			default: {
				for (int endCol = startCol + 2; endCol < line.length() - 2; ++endCol) {
					if (line.charAt(endCol) == endBracket //
							&& line.charAt(endCol + 1) == endBracket //
							&& ((endCol == line.length() - 2) || line.charAt(endCol + 2) != endBracket)) {

						final Position start = new Position(lineNumber, startCol);
						final Position end = new Position(lineNumber, endCol + 1);
						out.add(new Container(start, end, line.substring(startCol - 1, endCol)));
						break;

					}
				}
				// Else, nothing more on this line
				return;
			}
			}
			col = sts.getOffset() - 1;
		}
	}

	private boolean peek(ScannerTokenType expected) {
		return peek(expected, 1);
	}

	private ScannerToken peek() {
		return nextTokenIdx < tokens.size() ? tokens.get(nextTokenIdx) : null;
	}

	private boolean peek(ScannerTokenType expected, int offset) {
		final int idx = nextTokenIdx + offset - 1;
		return idx < tokens.size() && tokens.get(idx).type == expected;
	}

	private ScannerToken accept(ScannerTokenType expected) {
		if (nextTokenIdx >= tokens.size()) {
			return null;
		}
		final ScannerToken s = tokens.get(nextTokenIdx);
		if (s != null && s.type == expected) {
			++nextTokenIdx;
			return s;
		}
		return null;
	}

	private Container parseContainer() {
		final ScannerToken opener = accept(ScannerTokenType.CONTAINER_OPEN);
		Probe probe = parseStatement();
		ScannerToken closer = accept(ScannerTokenType.CONTAINER_CLOSE);
		if (probe == null || closer == null) {
			while (closer == null && peek() != null && peek().type != ScannerTokenType.CONTAINER_CLOSE) {
				++nextTokenIdx;
			}
			if (closer == null) {
				closer = accept(ScannerTokenType.CONTAINER_CLOSE);
				probe = null;
			}
		}
		if (closer == null) {
			return null;
		}
		return new Container( //
				opener.start, closer.end, //
				src.substring(opener.start.column + 1, closer.start.column - 1), //
				probe //
		);
	}

	private Probe parseStatement() {
		final ScannerToken s = peek();
		if (s == null) {
			return null;
		}

		switch (s.type) {
		case DOLLAR:
			if (peek(ScannerTokenType.ID, 2) && peek(ScannerTokenType.ASSIGN, 3)) {
				// VarDecl!
				final ScannerToken dollar = accept(ScannerTokenType.DOLLAR);
				final ScannerToken id = accept(ScannerTokenType.ID);
				final ScannerToken assign = accept(ScannerTokenType.ASSIGN);
				Query query = parseQuery(false);
				if (query == null) {
					// Situation: [[$name:=]]
					// Treat this as a query with empty type label
					final Position queryLoc = assign.end;
					query = new Query(queryLoc, queryLoc,
							QueryHead.fromType(new TypeQueryHead(queryLoc, false, new Label(queryLoc, queryLoc, ""))),
							null, Collections.emptyList());
				}

				return Probe.fromVarDecl(new VarDecl(dollar.start, query.end,
						new Label(dollar.start, id.end, id.value.toString()), query));
			}
			// Fall down to query

		default:
			final Query q = parseQuery(true);
			return q == null ? null : Probe.fromQuery(q);
		}
	}

	private Position startPos() {
		if (nextTokenIdx >= tokens.size()) {
			return new Position(0, 0);
		}
		return tokens.get(nextTokenIdx).start;
	}

	private Position endPos() {
		if (nextTokenIdx >= tokens.size()) {
			return new Position(0, 0);
		}
		final Position follow = tokens.get(nextTokenIdx).start;
		return new Position(follow.line, follow.column - 1);
	}

	private Query parseQuery(boolean allowAssertion) {
		final QueryHead head;
		ScannerToken headPeek = peek();
		if (headPeek == null) {
			return null;
		}
		Integer idx = null;
		switch (headPeek.type) {
		case CARET:
		case ID: {
			final ScannerToken caret = accept(ScannerTokenType.CARET);
			final ScannerToken id = accept(ScannerTokenType.ID);
			if (id == null) {
				head = QueryHead.fromType(new TypeQueryHead( //
						caret.start, true, new Label(caret.end, caret.end, "")));
				break;
			}
			Position idEnd = id.end;
			if (accept(ScannerTokenType.LBRACKET) != null) {
				ScannerToken idxToken = accept(ScannerTokenType.NUMBER);
				if (idxToken == null) {
					return null;
				}
				idx = (Integer) idxToken.value;
				final ScannerToken rbToken = accept(ScannerTokenType.RBRACKET);
				if (rbToken == null) {
					return null;
				}
				idEnd = rbToken.end;
			}
			head = QueryHead.fromType(new TypeQueryHead( //
					caret != null ? caret.start : id.start, //
					caret != null, //
					new Label(id.start, idEnd, id.value.toString())));
			break;
		}

		case DOLLAR: {
			accept(ScannerTokenType.DOLLAR);
			final ScannerToken id = accept(ScannerTokenType.ID);
			if (id == null) {
				return null;
			}
			Position idEnd = id.end;
			if (accept(ScannerTokenType.LBRACKET) != null) {
				ScannerToken idxToken = accept(ScannerTokenType.NUMBER);
				if (idxToken == null) {
					return null;
				}
				idx = (Integer) idxToken.value;
				final ScannerToken rbToken = accept(ScannerTokenType.RBRACKET);
				if (rbToken == null) {
					return null;
				}
				idEnd = rbToken.end;
			}
			head = QueryHead.fromVar(new VarUse(headPeek.start, idEnd, id.value.toString()));
			break;
		}

		default:
			return null;
		}

		List<PropertyAccess> propList = parsePropList();
		if (propList == null) {
			return null;
		}
		final Position nonAssertEnd = endPos();
		if (!allowAssertion) {
			return new Query(head.start, nonAssertEnd, head, idx, propList, null);
		}

		final ScannerToken exclamation = accept(ScannerTokenType.EXCLAMATION);
		final ScannerToken tilde = accept(ScannerTokenType.TILDE);
		final ScannerToken eq = accept(ScannerTokenType.EQ);
		if (exclamation == null && tilde == null && eq == null) {
			return new Query(head.start, nonAssertEnd, head, idx, propList);
		}
		if (eq == null) {
			if (exclamation != null && tilde == null) {
				// Shorthand "!", equal to "!=false"
				return new Query(head.start, exclamation.end, head, idx, propList,
						new QueryAssert(exclamation.start, exclamation.end, true, false, exclamation.start, //
								Expr.fromString(exclamation.start, exclamation.end, "false") //
								));
			}
			return null;
		}

		Expr expected = parseExpr();
		if (expected == null) {
			// Syntax sugar for equals empty string, no matter if
			// permitImplicitStringConversion is true or false.
			expected = Expr.fromString(startPos(), startPos(), "");
		}
		final QueryAssert qa = new QueryAssert( //
				exclamation != null ? exclamation.start : (tilde != null ? tilde.start : eq.start), //
				endPos(), //
				exclamation != null, tilde != null, eq.start, expected);
		return new Query(head.start, qa.end, head, idx, propList, //
				qa);
	}

	private Expr parseExpr() {
		ScannerToken st = peek();
		if (st == null) {
			return null;
		}

		switch (st.type) {
		case NUMBER:
			++nextTokenIdx;
			return Expr.fromInt(st.start, st.end, (int) st.value);
		case BOOL:
			++nextTokenIdx;
			return Expr.fromBoolean(st.start, st.end, (boolean) st.value);
		case STRING:
			++nextTokenIdx;
			return Expr.fromString(st.start, st.end, st.value.toString());
		case DOLLAR:
		case ID:
		case CARET:
			final Query query = parseQuery(false);
			return query == null ? null : Expr.fromQuery(query);
		default:
			return null;
		}
	}

	private List<PropertyAccess> parsePropList() {
		final List<PropertyAccess> propList = new ArrayList<>();
		while (peek(ScannerTokenType.DOT)) {
			accept(ScannerTokenType.DOT);

			if (!peek(ScannerTokenType.ID)) {
				break;
			}
			final ScannerToken propId = accept(ScannerTokenType.ID);

			Position argStart = null;
			Position argEnd = null;
			List<Expr> args = null;
			if (peek(ScannerTokenType.LPAREN)) {
				argStart = accept(ScannerTokenType.LPAREN).start;

				args = new ArrayList<>();

				while (true) {
					if (peek(ScannerTokenType.WHITESPACE)) {
						++nextTokenIdx;
					}
					final Expr expr = parseExpr();
					if (expr == null) {
						break;
					}
					args.add(expr);
					if (accept(ScannerTokenType.COMMA) == null) {
						break;
					}
				}

				ScannerToken rparen = accept(ScannerTokenType.RPAREN);
				if (rparen == null) {
					return null;
				}
				argEnd = rparen.end;
			}
			propList.add(new PropertyAccess(propId.start, argEnd != null ? argEnd : propId.end,
					new Label(propId.start, propId.end, propId.value.toString()), //
					argStart, args));
		}
		return propList;
	}
}
