#!/bin/sh
set -e

rm -rf build_tmp/
mkdir build_tmp

echo "Gathering sources.."
find src -name "*.java" > sources.txt

echo "Building.."
# "Our own" class files
javac @sources.txt -cp libs/json.jar -d build_tmp
# Third party class files
unzip libs/json.jar '*.class' -x */* -d build_tmp
# Resources
cp -r src/pasta/resources build_tmp/pasta/

cd build_tmp

echo "Generating jar.."
echo "Main-Class: pasta.PastaServer" >> Manifest.txt


VERSION=$(git rev-parse --short HEAD)
echo "Git-Version: $VERSION" >> cpr.properties
echo "status: $(git status --porcelain)"
if output=$(git status --porcelain) && [ -z "$output" ]; then
  # Working directory clean
  echo "Git-Status: CLEAN" >> cpr.properties
else
  # Uncommitted changes
  echo "Git-Status: DIRTY" >> cpr.properties
fi
echo "## Automatically generated by server/build.sh. Used by the client to detect when new versions are available. DO NOT MOIDFIFY\n$VERSION" > ../../VERSION

jar cfm ../../pasta-server.jar Manifest.txt cpr.properties **/*

cd ..

echo "Cleaning up.."
rm sources.txt
rm -rf build_tmp

echo "Done! Built 'pasta-server.jar'"
