#!/bin/sh
set -e

rm -rf build_tmp/
mkdir build_tmp

echo "Gathering sources.."
find src -name "*.java" > sources.txt

echo "Building.."
# "Our own" class files
javac @sources.txt -cp libs/json.jar -d build_tmp
# Third party class files
unzip libs/json.jar '*.class' -x */* -d build_tmp
# Resources
cp -r src/codeprober/resources build_tmp/codeprober/

cd build_tmp

echo "Generating jar.."
echo "Main-Class: codeprober.CodeProber" >> Manifest.txt

VERSION=$(git rev-parse --short HEAD)
echo "Git-Version: $VERSION" >> cpr.properties
if output=$(git status --porcelain) && [ -z "$output" ]; then
  echo "Git status is clean, this build can be released"
  echo "Git-Status: CLEAN" >> cpr.properties
  DST=../../code-prober.jar
  # VERSION is used to check when new versions are available
  # Only set it for release builds
  echo "## Automatically generated by server/build.sh. DO NOT MOIDFIFY\n$VERSION" > ../../VERSION
else
  echo "Git status is non-clean, this is a development build"
  echo "Git-Status: DIRTY" >> cpr.properties
  DST=../../code-prober-dev.jar
fi

jar cfm $DST Manifest.txt cpr.properties **/*

cd ..

echo "Cleaning up.."
rm sources.txt
rm -rf build_tmp

echo "Done! Built '$DST'"
