type SuffixAndAlias = [string, string];
const langstoSuffixes: { [key in SyntaxHighlightingLanguageId]: SuffixAndAlias} = {
  plaintext: [ 'txt', 'Plain Text' ],
  abap: [ 'abap', 'abap' ],
  apex: [ 'cls', 'Apex' ],
  azcli: [ 'azcli', 'Azure CLI' ],
  bat: [ 'bat', 'Batch' ],
  bicep: [ 'bicep', 'Bicep' ],
  cameligo: [ 'mligo', 'Cameligo' ],
  clojure: [ 'clj', 'clojure' ],
  coffeescript: [ 'coffee', 'CoffeeScript' ],
  c: [ 'c', 'C' ],
  cpp: [ 'cpp', 'C++' ],
  csharp: [ 'cs', 'C#' ],
  csp: [ 'csp', 'CSP' ],
  css: [ 'css', 'CSS' ],
  dart: [ 'dart', 'Dart' ],
  dockerfile: [ 'dockerfile', 'Dockerfile' ],
  ecl: [ 'ecl', 'ECL' ],
  elixir: [ 'ex', 'Elixir' ],
  flow9: [ 'flow', 'Flow9' ],
  fsharp: [ 'fs', 'F#' ],
  go: [ 'go', 'Go' ],
  graphql: [ 'graphql', 'GraphQL' ],
  handlebars: [ 'handlebars', 'Handlebars' ],
  hcl: [ 'tf', 'Terraform' ],
  html: [ 'html', 'HTML' ],
  ini: [ 'ini', 'Ini' ],
  java: [ 'java', 'Java' ],
  javascript: [ 'js', 'JavaScript' ],
  julia: [ 'jl', 'Julia' ],
  kotlin: [ 'kt', 'Kotlin' ],
  less: [ 'less', 'Less' ],
  lexon: [ 'lex', 'Lexon' ],
  lua: [ 'lua', 'Lua' ],
  liquid: [ 'liquid', 'Liquid' ],
  m3: [ 'm3', 'Modula-3' ],
  markdown: [ 'md', 'Markdown' ],
  mips: [ 's', 'MIPS' ],
  msdax: [ 'dax', 'DAX' ],
  mysql: [ 'mysql', 'MySQL' ],
  'objective-c': [ 'm', 'Objective-C' ],
  pascal: [ 'pas', 'Pascal' ],
  pascaligo: [ 'ligo', 'Pascaligo' ],
  perl: [ 'pl', 'Perl' ],
  pgsql: [ 'pgsql', 'PostgreSQL' ],
  php: [ 'php', 'PHP' ],
  postiats: [ 'dats', 'ATS' ],
  powerquery: [ 'pq', 'PQ' ],
  powershell: [ 'ps1', 'PowerShell' ],
  proto: [ 'proto', 'protobuf' ],
  pug: [ 'jade', 'Pug' ],
  python: [ 'py', 'Python' ],
  qsharp: [ 'qs', 'Q#' ],
  r: [ 'r', 'R' ],
  razor: [ 'cshtml', 'Razor' ],
  redis: [ 'redis', 'redis' ],
  redshift: [ 'redshift', 'Redshift' ],
  restructuredtext: [ 'rst', 'reStructuredText' ],
  ruby: [ 'rb', 'Ruby' ],
  rust: [ 'rs', 'Rust' ],
  sb: [ 'sb', 'Small Basic' ],
  scala: [ 'scala', 'Scala' ],
  scheme: [ 'scm', 'scheme' ],
  scss: [ 'scss', 'Sass' ],
  shell: [ 'sh', 'Shell' ],
  sol: [ 'sol', 'sol' ],
  aes: [ 'aes', 'aes' ],
  sparql: [ 'rq', 'sparql' ],
  sql: [ 'sql', 'SQL' ],
  st: [ 'st', 'StructuredText' ],
  swift: [ 'swift', 'Swift' ],
  systemverilog: [ 'sv', 'SV' ],
  verilog: [ 'v', 'V' ],
  tcl: [ 'tcl', 'tcl' ],
  teal: [ 'teal', 'TEAL' ],
  twig: [ 'twig', 'Twig' ],
  typescript: [ 'ts', 'TypeScript' ],
  vb: [ 'vb', 'Visual Basic' ],
  xml: [ 'xml', 'XML' ],
  yaml: [ 'yaml', 'YAML' ],
  json: [ 'json', 'JSON' ]
};

const getAppropriateFileSuffix = (lang: SyntaxHighlightingLanguageId) => {
  return langstoSuffixes[lang]?.[0] ?? `.${lang.toLowerCase()}`;
}
const getAvailableLanguages = (): { id: string, alias: string }[] => Object.assign(Object.entries(langstoSuffixes).map(([k, v]) => ({ id: k, alias: v[1] })));
export { getAppropriateFileSuffix, getAvailableLanguages }
